version: "3"

services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - pg