export const DATA_SOURCE = 'DATA_SOURCE';
export const WALLET_REPOSITORY = 'WALLET_REPOSITORY';
export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
export const STAKE_REPOSITORY = 'STAKE_REPOSITORY';
