name: Deploy Server

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      env:
        URL: "git@github.com:liketurbo/falcor-backend.git"
        FOLDER: "falcor-backend"
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          mkdir -p projects
          cd projects
          if [ ! -d "$FOLDER" ] ; then git clone "$URL" "$FOLDER" ; else cd "$FOLDER" ; git pull "$URL" ; fi